Item(by='kmill', descendants=None, kids=None, score=None, time=1604271332, title=None, item_type='comment', url=None, parent=24963140, text='Resumable exceptions are still used in Common Lisp, in the form of the condition system. There have been a few recent posts about it on HN, including one about a new book.<p>I think the key is that the system lets you specify multiple resumption points, so then the exception handler can make an intelligent decision of how to resume.')