Item(by='Phlogistique', descendants=None, kids=None, score=None, time=1606753234, title=None, item_type='comment', url=None, parent=25254725, text='Well, what this API&#x27;s implementer could have done, is to catch the IOException and throw RuntimeException. That makes sense, because there is no reason during normal program operation for this API to throw IOException, so if it does it must be an internal bug in the library.<p>This pattern is equivalent to Rust&#x27;s `unwrap` and `expect`, than can be called to transform a recoverable error into a panic.')