Item(by='jdeibele', descendants=None, kids=None, score=None, time=1606768406, title=None, item_type='comment', url=None, parent=25253236, text='pip-review works great for keeping packages up to date.<p><a href="https:&#x2F;&#x2F;pypi.org&#x2F;project&#x2F;pip-review&#x2F;" rel="nofollow">https:&#x2F;&#x2F;pypi.org&#x2F;project&#x2F;pip-review&#x2F;</a><p>&gt; pip-review\nFaker==4.18.0 is available (you have 4.17.1)\npip==20.3 is available (you have 20.2.4)<p>&gt; pip-review --auto --verbose\nCollecting Faker==4.18.0\n  Downloading Faker-4.18.0-py3-none-any.whl (1.1 MB)\n     || 1.1 MB 730 kB&#x2F;s \nCollecting pip==20.3\n  Downloading pip-20.3-py2.py3-none-any.whl (1.5 MB)\n     || 1.5 MB 2.0 MB&#x2F;s \nRequirement already satisfied: python-dateutil&gt;=2.4 in &#x2F;usr&#x2F;local&#x2F;lib&#x2F;python3.8&#x2F;site-packages (from Faker==4.18.0) (2.8.1)\nRequirement already satisfied: text-unidecode==1.3 in &#x2F;usr&#x2F;local&#x2F;lib&#x2F;python3.8&#x2F;site-packages (from Faker==4.18.0) (1.3)\nRequirement already satisfied: six&gt;=1.5 in &#x2F;usr&#x2F;local&#x2F;lib&#x2F;python3.8&#x2F;site-packages (from python-dateutil&gt;=2.4-&gt;Faker==4.18.0) (1.15.0)\nInstalling collected packages: Faker, pip\n  Attempting uninstall: Faker\n    Found existing installation: Faker 4.17.1\n    Uninstalling Faker-4.17.1:\n      Successfully uninstalled Faker-4.17.1\n  Attempting uninstall: pip\n    Found existing installation: pip 20.2.4\n    Uninstalling pip-20.2.4:\n      Successfully uninstalled pip-20.2.4\nERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.<p>We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.<p>lektor 3.2.0 requires Werkzeug&lt;1, but you&#x27;ll have werkzeug 1.0.1 which is incompatible.\nSuccessfully installed Faker-4.18.0 pip-20.3')