Item(by='AnimalMuppet', descendants=None, kids=None, score=None, time=1606760613, title=None, item_type='comment', url=None, parent=25255287, text='Almost.  The right answer is to throw new JsonParseException(e) instead.  That says that yes, this exception <i>can</i> happen, it&#x27;s a JSON parse error.  But the &quot;outer&quot; exception stack trace will lead to this catch block, which doesn&#x27;t give all the information.  But the exception wraps the &quot;inner&quot; exception, which has the stack trace to where the actual problem was detected.  But the inner exception had the wrong type (IOException), so you wrap it with the outer exception to correctly convey what went wrong.')