Item(by='chaorace', descendants=None, kids=None, score=None, time=1606922831, title=None, item_type='comment', url=None, parent=25267453, text='My bad! Text is funny sometimes, isn&#x27;t it?<p>I agree with your basic argument here and you&#x27;ve convinced me to some extent. I wanted to dredge up some examples to highlight inherent flaws in Python&#x27;s error handling ergonomics, <i>but</i> I was pleasantly surprised by new language features that made the experience much more enjoyable (the with ... as keywords, in particular).<p>I will say this though: try&#x2F;except still sucks, in my opinion. I much prefer languages whose standard libraries utilize monads&#x2F;callbacks for error handling, because it offloads much of the work&#x2F;documentation onto the type system, as opposed to languages&#x2F;frameworks which prefer error handling as part of a try&#x2F;catch statement.<p>Monad Example (Scala documentation - Try monad <i>[1]</i> ):<p><pre><code>  import scala.util.{Try, Success, Failure}\n\n  def divide: Try[Int] = {\n    val dividend = Try(Console.readLine(&quot;Enter an Int that you&#x27;d like to divide:\\n&quot;).toInt)\n    val divisor = Try(Console.readLine(&quot;Enter an Int that you&#x27;d like to divide by:\\n&quot;).toInt)\n    val problem = dividend.flatMap(x =&gt; divisor.map(y =&gt; x&#x2F;y))\n    problem match {\n      case Success(v) =&gt;\n        println(&quot;Result of &quot; + dividend.get + &quot;&#x2F;&quot;+ divisor.get +&quot; is: &quot; + v)\n        Success(v)\n      case Failure(e) =&gt;\n        println(&quot;You must&#x27;ve divided by zero or entered something that&#x27;s not an Int. Try again!&quot;)\n        println(&quot;Info from the exception: &quot; + e.getMessage)\n        divide\n    }\n  }\n</code></pre>\nCallback Example (NodeJS documentation - fs.readFile function <i>[2]</i> ):<p><pre><code>  fs.readFile(&#x27;&#x2F;etc&#x2F;passwd&#x27;, (err, data) =&gt; {\n    if (err) throw err;\n    console.log(data);\n  });\n</code></pre>\n[1]: <a href="https:&#x2F;&#x2F;www.scala-lang.org&#x2F;api&#x2F;2.9.3&#x2F;scala&#x2F;util&#x2F;Try.html" rel="nofollow">https:&#x2F;&#x2F;www.scala-lang.org&#x2F;api&#x2F;2.9.3&#x2F;scala&#x2F;util&#x2F;Try.html</a>\n[2]: <a href="https:&#x2F;&#x2F;nodejs.org&#x2F;api&#x2F;fs.html#fs_fs_readfile_path_options_callback" rel="nofollow">https:&#x2F;&#x2F;nodejs.org&#x2F;api&#x2F;fs.html#fs_fs_readfile_path_options_c...</a>')