Item(by='pfalcon', descendants=None, kids=[25622292], score=None, time=1609687138, title=None, item_type='comment', url=None, parent=25622106, text='Sorry, but throwing an exception in a function call is equivalent to:<p><pre><code>    res, exc = fun();\n    if (exc) goto exception_handler;\n</code></pre>\nThat&#x27;s underlying model of how exceptions behave, and how they&#x27;re implemented &quot;manually&quot; in languages with no exception handling (C, Go). You absolutely can draw that by examining syntax of a subroutine, and it&#x27;s no more implicit than &quot;defer&quot;.')