Item(by='benmmurphy', descendants=None, kids=[25737642], score=None, time=1610370486, title=None, item_type='comment', url=None, parent=25726744, text='They make a request to twilio and their logic checks for a failure response instead of looking for a success response. They are not getting back a different failure response and this causes the requests to be incorrectly be marked as success.<p>For example here is how something like that might break:<p><pre><code>    &#x2F;auth \n    -&gt; returns {&quot;success&quot;: true} and 200 on success\n    -&gt; normally returns {&quot;success&quot;: false, &quot;error&quot;: &quot;BLAHLBAH&quot;} and 200 on failure\n</code></pre>\ndeveloper checks if response[&quot;error&quot;] is null to check if it was successful or not<p>after your account is disabled &#x2F;auth starts returning empty json: {} with a 500 error code<p>oops. now all the requests are incorrectly marked as success. i know this happens because i&#x27;ve seen similar things happen in real life.<p>the error could also be more obvious and the code just fails open. someone has a try&#x2F;catch and returns true either because of an accidental mistake or because they don&#x27;t want users to be locked out when the provider is down.')