Item(by='throw_m239339', descendants=None, kids=None, score=None, time=1610754377, title=None, item_type='comment', url=None, parent=25798107, text='&gt; Pretty sure Go doesn&#x27;t have throw&#x2F;catch.<p>Go has panic&#x2F;recover, which are basically exceptions with some different scoping rules.')