Item(by='groodt', descendants=260, kids=[25889412, 25890486, 25888991, 25889328, 25888452, 25888803, 25889025, 25889049, 25888819, 25888463, 25888897, 25889455, 25889462, 25890237, 25889807, 25888552, 25888925, 25888658, 25889170, 25889901, 25888475, 25888511, 25888730], score=366, time=1611453703, title='Pip has dropped support for Python 2', item_type='story', url='https://pip.pypa.io/en/stable/news/#id1', parent=None, text=None)