Item(by='my123', descendants=None, kids=None, score=None, time=1612010995, title=None, item_type='comment', url=None, parent=25968512, text='&gt; Many system calls will report the EINTR error code if a signal occurred while the system call was in progress. No error actually occurred, it&#x27;s just reported that way because the system isn&#x27;t able to resume the system call automatically. This coding pattern simply retries the system call when this happens, to ignore the interrupt.<p>&gt; For instance, this might happen if the program makes use of alarm() to run some code asynchronously when a timer runs out. If the timeout occurs while the program is calling write(), we just want to retry the system call (aka read&#x2F;write, etc).<p>It&#x27;s perfectly valid behaviour, and the solution is to retry in that case.')